export default [
	'~/assets/css/style.css',
	'~/assets/css/responsive.css',
	'~/assets/css/custom-animation.css',
	'~/assets/css/vendor/bootstrap/css/bootstrap.min.css',
	'~/assets/css/vendor/mega-menu/assets/css/menu.css',
	'~/assets/css/vendor/owl-carousel/owl.carousel.css',
	'~/assets/css/vendor/owl-carousel/owl.theme.css',
	'~/assets/css/vendor/owl-carousel/animate.css',
	'~/assets/css/vendor/aos-next/dist/aos.css',
	'~/assets/css/vendor/fancybox/dist/jquery.fancybox.min.css',
	'~/assets/css/vendor/sanzzy-map/dist/snazzy-info-window.min.css',
	'~/assets/css/vendor/animated-headline-master/style.css',
	'~/assets/css/vendor/iziModal-master/iziModal.css',
	'~/assets/css/vendor/tabs/tabs.css',
]
